### Test Preprocessing

In [20]:
from VideoGame import utils

In [10]:
text = '''Well organized and easy to understand Web building..& @
tutorials with 898 lots of examples of how to use HTML, CSS, JavaScript, SQL, 
PHP, Python, Bootstrap, Java and XML.'''

In [11]:
utils.preprocess(text)

'well organized easy understand web building tutorial lot example use html cs javascript sql php python bootstrap java xml'

In [4]:
from packages.preprocess import *

In [5]:
lemmatizer(text)

'Well organized and easy to understand Web building .. & @ tutorial with 898 lot of example of how to use HTML , CSS , JavaScript , SQL , PHP , Python , Bootstrap , Java and XML .'

In [7]:
!tree

.
├── Capstone_project_2
│   ├── Report
│   │   ├── Amazon_sentiment_analysis_presentation.pdf
│   │   ├── Capstone\ project\ 2\ ideas.pdf
│   │   ├── Final_report_capstone2.pdf
│   │   ├── Milestone_report1_capstone2.pdf
│   │   ├── Milestone_report2_capstone2.pdf
│   │   ├── Project_proposal_capstone_2.pdf
│   │   └── readme.md
│   ├── code
│   │   ├── Amazon-Headphones_data_wrangling.ipynb
│   │   ├── Amazon-headphones_EDA.ipynb
│   │   ├── Amazon_headphones_Sentiment_Analysis_CV_IF_IDF_HASH.ipynb
│   │   ├── Amazon_headphones_wordvec.ipynb
│   │   ├── amazon_electronics_recommendation.ipynb
│   │   ├── big.txt
│   │   ├── contractions.py
│   │   └── readme.md
│   └── readme.md
├── Notebooks
│   ├── DataPreproc.ipynb
│   ├── Recommendation.ipynb
│   ├── binary.pkl
│   ├── content\ based\ recommendation.ipynb
│   ├── data_user_prod.pickle
│   ├── df_user_prod.pickle
│   ├── preprocessed.pkl
│   ├── product_review_df.pickle
│   ├── product_review_df.pickle.zip
│   ├── requirements.
│ 

### Test Load Latent df

In [1]:
from VideoGame.contentBasedRec import ContentRecommender

In [2]:
rec = ContentRecommender()


In [3]:
rec.get_recommendation()

['The Legend of Legacy',
 'Girls RPG: Cinderellife',
 'Inazuma Eleven Go 2: Chrono Stone',
 'Yokai Watch 2 Shinuchi',
 'Medabots Girls Mission: Metabee Ver. / Rokusho Ver.']

## Try get game list

In [1]:
from VideoGame import utils

In [2]:
utils.get_model()

Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1, class_prior=None, fit_prior=True))])

## Try Load Data from Google Cloud


## Try load Model

In [20]:
from pkg import utils

In [21]:
model = utils.get_model()

In [22]:
import pickle
with open(r"NaiveBayes.pickle", "wb") as output_file:
    pickle.dump(model, output_file)

In [23]:
with open(r"NaiveBayes.pickle", "rb") as file:
    model = pickle.load(file)

In [24]:
model.predict(['''Graphics and gameplay were good. 
The game is somewhat linear and not a lot of different 
things to do, but still pretty fun'''])

array([1])

## Try Load Model from GC

In [15]:
from google.cloud import storage

In [16]:
import os

In [18]:
credentials_raw = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')

In [19]:
from google.cloud import storage
from sklearn.externals import joblib

storage_client = storage.Client()
bucket_name=<bucket name>
model_bucket='model.joblib'
model_local='local.joblib'

bucket = storage_client.get_bucket(bucket_name)
#select bucket file
blob = bucket.blob(model_bucket)
#download that file and name it 'local.joblib'
blob.download_to_filename(model_local)
#load that file from local file
job=joblib.load(model_local)

In [20]:
from google.cloud import storage
from sklearn.externals import joblib

In [56]:
credentials_raw = open('access.json').read()

In [26]:
import json
creds_json = json.loads(credentials_raw)

In [27]:
from google.oauth2 import service_account
creds_gcp = service_account.Credentials.from_service_account_info(creds_json)

In [58]:
import pickle

with open (r"creds_gcp.plk", "wb") as file:
    pickle.dump(credentials_raw, file)


In [29]:
# video-game-rec-99/Model/Logistic.joblib

client = storage.Client(credentials=creds_gcp, 
                        project="amazonreview-297414").bucket("video-game-rec-99")



In [43]:
storage_location = 'Model/NaiveBayes.joblib'

In [44]:
blob = client.blob(storage_location)

In [45]:
blob.download_to_filename('Logistic.joblib')

In [46]:
model = joblib.load('Logistic.joblib')

In [35]:
import joblib

In [47]:
model = joblib.load("Logistic.joblib")

In [48]:
model.predict(["I have to be honest.. When I first started the game, it was rather boring BUT everyone told me that I was still in the prologue and that once the actual game started, the action and story would pick up dramatically. They were right! Not only are the graphics amazing, but the game overall is beautiful. The action is intense, and I found myself actually getting invested in a few of the characters\' storylines. Very good game!"])

array([1])

In [49]:
string = 'Opened my amazon package to see the game box crushed and a corner of the plastic completely separated from the disc holder, disc was loosely moving inside the game box\'s casing probably for the entirety of the shipping.  Highly recommend picking up somewhere. Game seems to work but I have a feeling I\'ll get to a point and it will skip endlessly due to some scratching..'

In [50]:
model.predict([string])

array([0])

In [52]:
'Models/{}.joblib'.format(13)

'Models/13.joblib'

## Test Video Game list

In [1]:
from pkg import utils


In [2]:
len(utils.get_game_lst())

11562

In [3]:
len(set(utils.get_game_lst()))

11562

In [4]:
import pandas as pd
Catelog = pd.read_csv("pkg/data/Catelog.csv")

In [5]:
Catelog.shape

(11562, 6)

In [6]:
from pkg import utils

In [8]:
latent_df = pd.read_csv("pkg/data/latent_df.csv")
latent_df

Unnamed: 0         0         1  \
0                                     Beyblade Burst  0.453322  0.534898   
1                                  Fire Emblem Fates  0.497696  0.569931   
2                               Frozen: Olaf's Quest  0.246889  0.033112   
3                         Haikyu!! Cross Team Match!  0.759435  1.156337   
4                                  Tales of Xillia 2  1.113083  1.586984   
5                                        '98 Koshien  0.363361 -0.250729   
6                         .hack//G.U. Vol.1//Rebirth  1.344304  1.471312   
7                       .hack//G.U. Vol.2//Reminisce  1.344304  1.471312   
8            .hack//G.U. Vol.2//Reminisce (jp sales)  1.344304  1.471312   
9                      .hack//G.U. Vol.3//Redemption  1.344304  1.471312   
10                           .hack//Infection Part 1  0.753717  0.378267   
11                                       .hack//Link  1.134749  1.616670   
12                            .hack//Mutation Part 2  0.753717  0.378267   
13                            .hack//Outbreak Part 3  0.753717  0.378267   
14       .hack//Quarantine Part 4: The Final Chapter  0.753717  0.378267   
15                 .hack: Sekai no Mukou ni + Versus  0.995131  1.218467   
16                                        007 Racing  0.353173 -0.175072   
17                            007: Quantum of Solace  0.366771  0.130327   
18                      007: The World is not Enough  0.430070  0.060046   
19                          007: Tomorrow Never Dies  0.356630 -0.165011   
20                                         1 vs. 100  0.687847  0.647877   
21                                      1/2 Summer +  0.222534  0.045859   
22                                10 Minute Solution  0.331390 -0.121558   
23                            100 All-Time Favorites  0.334959  0.227352   
24                                 100 Classic Books  0.465357  0.232423   
25                                 100 Classic Games  0.419377  0.195833   
26            1000 Cooking Recipes from ELLE à table  0.465357  0.232423   
27                                  1001 Touch Games  0.537037  0.298458   
28                        101-in-1 Explosive Megamix  0.289575  0.208350   
29                        101-in-1 Party Megamix Wii  0.267449  0.029327   
...                                              ...       ...       ...   
11532                             Zumba Fitness Core  0.556148  0.509185   
11533                             Zumba Fitness Rush  0.536411  0.345614   
11534                     Zumba Fitness: World Party  0.636869 -0.470943   
11535                                         Zwei!!  0.534407  0.528897   
11536  Zyuden Sentai Kyoryuger: Game de Gaburincho!!  0.943862  1.261734   
11537                                  [Prototype 2]  0.366771  0.130327   
11538                                    [Prototype]  0.366771  0.130327   
11539                                        de Blob  0.179479  0.001785   
11540                                      de Blob 2  0.180713 -0.007790   
11541                                 eJay Clubworld  0.614445 -0.105651   
11542                                     echochrome  0.947798 -0.788737   
11543                  ef - a fairy tale of the two.  0.431675 -0.099855   
11544                                       everGirl  0.192229  0.009334   
11545                 futureU: The Prep Game for SAT  0.419237  0.195842   
11546                    htoL#NiQ: The Firefly Diary  0.117693  0.031804   
11547                                         iCarly  0.384307  0.197766   
11548                     iCarly 2: iJoin The Click!  0.384307  0.197766   
11549                                       inFAMOUS  1.171861 -0.729689   
11550                                     inFAMOUS 2  1.171861 -0.729689   
11551                           inFAMOUS: Second Son  1.107635 -0.732555   
11552                                         nail'd  0.177133 -0.013891   
11553         

In [19]:
utils.get_latent_df()

0         1         2  \
Unnamed: 0                                                                    
 Beyblade Burst                                0.453322  0.534898  1.184227   
 Fire Emblem Fates                             0.497696  0.569931  1.224887   
 Frozen: Olaf's Quest                          0.246889  0.033112 -0.074443   
 Haikyu!! Cross Team Match!                    0.759435  1.156337 -0.607655   
 Tales of Xillia 2                             1.113083  1.586984  0.588895   
'98 Koshien                                    0.363361 -0.250729 -0.037570   
.hack//G.U. Vol.1//Rebirth                     1.344304  1.471312  0.608095   
.hack//G.U. Vol.2//Reminisce                   1.344304  1.471312  0.608095   
.hack//G.U. Vol.2//Reminisce (jp sales)        1.344304  1.471312  0.608095   
.hack//G.U. Vol.3//Redemption                  1.344304  1.471312  0.608095   
.hack//Infection Part 1                        0.753717  0.378267  1.187305   
.hack//Link                                    1.134749  1.616670  0.671630   
.hack//Mutation Part 2                         0.753717  0.378267  1.187305   
.hack//Outbreak Part 3                         0.753717  0.378267  1.187305   
.hack//Quarantine Part 4: The Final Chapter    0.753717  0.378267  1.187305   
.hack: Sekai no Mukou ni + Versus              0.995131  1.218467 -0.961679   
007 Racing                                     0.353173 -0.175072 -0.047838   
007: Quantum of Solace                         0.366771  0.130327 -0.385995   
007: The World is not Enough                   0.430070  0.060046 -0.407086   
007: Tomorrow Never Dies                       0.356630 -0.165011 -0.056661   
1 vs. 100                                      0.687847  0.647877 -0.350588   
1/2 Summer +                                   0.222534  0.045859  0.030919   
10 Minute Solution                             0.331390 -0.121558 -0.141339   
100 All-Time Favorites                         0.334959  0.227352 -0.053578   
100 Classic Books                              0.465357  0.232423 -0.064376   
100 Classic Games                              0.419377  0.195833 -0.106291   
1000 Cooking Recipes from ELLE à table         0.465357  0.232423 -0.064376   
1001 Touch Games                               0.537037  0.298458 -0.387919   
101-in-1 Explosive Megamix                     0.289575  0.208350 -0.041956   
101-in-1 Party Megamix Wii                     0.267449  0.029327 -0.153256   
...                                                 ...       ...       ...   
Zumba Fitness Core                             0.556148  0.509185 -0.413351   
Zumba Fitness Rush                             0.536411  0.345614 -0.323227   
Zumba Fitness: World Party                     0.636869 -0.470943 -0.041023   
Zwei!!                                         0.534407  0.528897  1.273604   
Zyuden Sentai Kyoryuger: Game de Gaburincho!!  0.943862  1.261734 -0.942853   
[Prototype 2]                                  0.366771  0.130327 -0.385995   
[Prototype]                                    0.366771  0.130327 -0.385995   
de Blob                                        0.179479  0.001785 -0.098199   
de Blob 2                                      0.180713 -0.007790 -0.050954   
eJay Clubworld                                 0.614445 -0.105651 -0.131522   
echochrome                                     0.947798 -0.788737  0.154231   
ef - a fairy tale of the two.                  0.431675 -0.099855 -0.031837   
everGirl                                       0.192229  0.009334 -0.036564   
futureU: The Prep Game for SAT                 0.419237  0.195842 -0.105604   
htoL#NiQ: The Firefly Diary                    0.117693  0.031804  0.087197   
iCarly                                         0.384307  0.197766 -0.066837   
iCarly 2: iJoin The Click!                     0.384307  0.197766 -0.066837   
inFAMOUS                                       1.171861 -0.729689 -0.273339   
inFAMOUS 2               